/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hall.dining.managemeent.system;

import dao.UserDao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sami
 */
public class ChangePassword extends javax.swing.JFrame {
    
    public String userEmail; 
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        eyeCloseOld.setVisible(false);
        eyeCloseNew.setVisible(false);
        eyeCloseConfirm.setVisible(false);
    }
    
     public ChangePassword(String email) {
        initComponents();
        userEmail = email; 
        btnUpdate.setEnabled(false);
        eyeCloseOld.setVisible(false);
        eyeCloseNew.setVisible(false);
        eyeCloseConfirm.setVisible(false);
    }
     
     public void validateField()
     {
         String oldPassword = txtOldPassword.getText();
         String newPassword = txtNewPassword.getText();
         String confirmPassword = txtConfirmPassword.getText();
         
         if(!oldPassword.equals("") && !newPassword.equals("") && !confirmPassword.equals("") && newPassword.equals(confirmPassword))
         {
             btnUpdate.setEnabled(true);
         }
         else
         {
             btnUpdate.setEnabled(false);
         }
     }
     
     public void clear()
     {
         btnUpdate.setEnabled(false);
         txtOldPassword.setText("");
         txtNewPassword.setText("");
         txtConfirmPassword.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonRectangleBeanInfo1 = new rojerusan.RSMaterialButtonRectangleBeanInfo();
        rSMaterialButtonCircleBeanInfo1 = new rojerusan.RSMaterialButtonCircleBeanInfo();
        rSMaterialButtonCircleBeanInfo2 = new rojerusan.RSMaterialButtonCircleBeanInfo();
        rSMaterialButtonCircleBeanInfo3 = new rojerusan.RSMaterialButtonCircleBeanInfo();
        rSMaterialButtonCircleBeanInfo4 = new rojerusan.RSMaterialButtonCircleBeanInfo();
        rSMaterialButtonRectangleBeanInfo2 = new rojerusan.RSMaterialButtonRectangleBeanInfo();
        rSMaterialButtonCircleBeanInfo5 = new rojerusan.RSMaterialButtonCircleBeanInfo();
        evaluatorArc2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorArc2D();
        materialButton1 = new necesario.MaterialButton();
        eyeOpen1 = new javax.swing.JLabel();
        eyeOpen3 = new javax.swing.JLabel();
        eyeClose1 = new javax.swing.JLabel();
        blue = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBack = new javax.swing.JLabel();
        blue2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBack2 = new javax.swing.JLabel();
        txtOldPassword2 = new javax.swing.JPasswordField();
        txtNewPassword2 = new javax.swing.JPasswordField();
        txtConfirmPassword2 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnClear2 = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel18 = new javax.swing.JLabel();
        eyeOpen5 = new javax.swing.JLabel();
        eyeOpen6 = new javax.swing.JLabel();
        eyeOpen7 = new javax.swing.JLabel();
        eyeClose2 = new javax.swing.JLabel();
        blue3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jBack3 = new javax.swing.JLabel();
        txtOldPassword3 = new javax.swing.JPasswordField();
        txtNewPassword3 = new javax.swing.JPasswordField();
        txtConfirmPassword3 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnClear3 = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate3 = new rojerusan.RSMaterialButtonRectangle();
        jLabel23 = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        jLabel10 = new javax.swing.JLabel();
        blue1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBack1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnClear1 = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate1 = new rojerusan.RSMaterialButtonRectangle();
        eyeOpenOld = new javax.swing.JLabel();
        eyeCloseNew = new javax.swing.JLabel();
        eyeCloseConfirm = new javax.swing.JLabel();
        eyeCloseOld = new javax.swing.JLabel();
        eyeOpenNew = new javax.swing.JLabel();
        eyeOpenConfirm = new javax.swing.JLabel();

        materialButton1.setText("materialButton1");

        eyeOpen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpen1MouseClicked(evt);
            }
        });

        eyeOpen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpen3MouseClicked(evt);
            }
        });

        eyeClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-hide-25.png"))); // NOI18N
        eyeClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeClose1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blue.setBackground(new java.awt.Color(255, 255, 255));
        blue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dyuthi", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcon/icons8-lock-orientation-50.png"))); // NOI18N
        jLabel9.setText("  Change Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack.setForeground(new java.awt.Color(255, 255, 255));
        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack.setText("Back");
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        jPanel1.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        blue2.setBackground(new java.awt.Color(255, 255, 255));
        blue2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Dyuthi", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcon/icons8-lock-orientation-50.png"))); // NOI18N
        jLabel14.setText("  Change Password");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack2.setForeground(new java.awt.Color(255, 255, 255));
        jBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack2.setText("Back");
        jBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack2MouseClicked(evt);
            }
        });
        jPanel6.add(jBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        blue2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 305, 560));

        txtOldPassword2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtOldPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPassword2ActionPerformed(evt);
            }
        });
        txtOldPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldPassword2KeyReleased(evt);
            }
        });
        blue2.add(txtOldPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 179, 242, -1));

        txtNewPassword2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtNewPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPassword2KeyReleased(evt);
            }
        });
        blue2.add(txtNewPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 240, 242, -1));

        txtConfirmPassword2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtConfirmPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPassword2KeyReleased(evt);
            }
        });
        blue2.add(txtConfirmPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 296, 242, -1));

        jLabel15.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel15.setText("Old Password");
        blue2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 179, -1, -1));

        jLabel16.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel16.setText("New Password");
        blue2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel17.setText("Confirm Password");
        blue2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 296, -1, -1));

        btnClear2.setBackground(new java.awt.Color(255, 51, 51));
        btnClear2.setText("Clear");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        blue2.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 399, 150, 51));

        btnUpdate2.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate2.setText("Update Password");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        blue2.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 399, 150, 51));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-cross-30.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        blue2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 6, -1, -1));

        eyeOpen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpen5MouseClicked(evt);
            }
        });
        blue2.add(eyeOpen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        eyeOpen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpen6MouseClicked(evt);
            }
        });
        blue2.add(eyeOpen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, -1, -1));

        eyeOpen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpen7MouseClicked(evt);
            }
        });
        blue2.add(eyeOpen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, -1, -1));

        eyeClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-hide-25.png"))); // NOI18N
        eyeClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeClose2MouseClicked(evt);
            }
        });
        blue2.add(eyeClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        blue3.setBackground(new java.awt.Color(255, 255, 255));
        blue3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dyuthi", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcon/icons8-lock-orientation-50.png"))); // NOI18N
        jLabel19.setText("  Change Password");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack3.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack3.setForeground(new java.awt.Color(255, 255, 255));
        jBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack3.setText("Back");
        jBack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack3MouseClicked(evt);
            }
        });
        jPanel8.add(jBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        blue3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 305, 560));

        txtOldPassword3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtOldPassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPassword3ActionPerformed(evt);
            }
        });
        txtOldPassword3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldPassword3KeyReleased(evt);
            }
        });
        blue3.add(txtOldPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 179, 242, -1));

        txtNewPassword3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtNewPassword3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPassword3KeyReleased(evt);
            }
        });
        blue3.add(txtNewPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 240, 242, -1));

        txtConfirmPassword3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtConfirmPassword3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPassword3KeyReleased(evt);
            }
        });
        blue3.add(txtConfirmPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 296, 242, -1));

        jLabel20.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel20.setText("Old Password");
        blue3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 179, -1, -1));

        jLabel21.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel21.setText("New Password");
        blue3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 240, -1, -1));

        jLabel22.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel22.setText("Confirm Password");
        blue3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 296, -1, -1));

        btnClear3.setBackground(new java.awt.Color(255, 51, 51));
        btnClear3.setText("Clear");
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });
        blue3.add(btnClear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 399, 150, 51));

        btnUpdate3.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate3.setText("Update Password");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });
        blue3.add(btnUpdate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 399, 150, 51));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-cross-30.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        blue3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 6, -1, -1));

        blue2.add(blue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        jPanel2.add(blue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        blue.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 305, 560));

        txtOldPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtOldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPasswordActionPerformed(evt);
            }
        });
        txtOldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldPasswordKeyReleased(evt);
            }
        });
        blue.add(txtOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 179, 242, -1));

        txtNewPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyReleased(evt);
            }
        });
        blue.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 240, 242, -1));

        txtConfirmPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyReleased(evt);
            }
        });
        blue.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 296, 242, -1));

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel2.setText("Old Password");
        blue.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 179, -1, -1));

        jLabel3.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel3.setText("New Password");
        blue.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel4.setText("Confirm Password");
        blue.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 296, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        blue.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 399, 150, 51));

        btnUpdate.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate.setText("Update Password");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        blue.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 399, 150, 51));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-cross-30.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        blue.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 6, -1, -1));

        blue1.setBackground(new java.awt.Color(255, 255, 255));
        blue1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Dyuthi", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcon/icons8-lock-orientation-50.png"))); // NOI18N
        jLabel11.setText("  Change Password");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack1.setForeground(new java.awt.Color(255, 255, 255));
        jBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack1.setText("Back");
        jBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack1MouseClicked(evt);
            }
        });
        jPanel4.add(jBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        blue1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 305, 560));

        jLabel5.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel5.setText("Old Password");
        blue1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 179, -1, -1));

        jLabel6.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel6.setText("New Password");
        blue1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("URW Chancery L", 1, 20)); // NOI18N
        jLabel12.setText("Confirm Password");
        blue1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 296, -1, -1));

        btnClear1.setBackground(new java.awt.Color(255, 51, 51));
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        blue1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 399, 150, 51));

        btnUpdate1.setBackground(new java.awt.Color(255, 51, 51));
        btnUpdate1.setText("Update Password");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        blue1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 399, 150, 51));

        eyeOpenOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpenOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpenOldMouseClicked(evt);
            }
        });
        blue1.add(eyeOpenOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, -1));

        eyeCloseNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-hide-25.png"))); // NOI18N
        eyeCloseNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeCloseNewMouseClicked(evt);
            }
        });
        blue1.add(eyeCloseNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        eyeCloseConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-hide-25.png"))); // NOI18N
        eyeCloseConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeCloseConfirmMouseClicked(evt);
            }
        });
        blue1.add(eyeCloseConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, 30));

        eyeCloseOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-hide-25.png"))); // NOI18N
        eyeCloseOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeCloseOldMouseClicked(evt);
            }
        });
        blue1.add(eyeCloseOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, -1));

        eyeOpenNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpenNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpenNewMouseClicked(evt);
            }
        });
        blue1.add(eyeOpenNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        eyeOpenConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-eye-25.png"))); // NOI18N
        eyeOpenConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeOpenConfirmMouseClicked(evt);
            }
        });
        blue1.add(eyeOpenConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        blue.add(blue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String oldPassword = txtOldPassword.getText();
        String newPassword = txtNewPassword.getText();
        
        UserDao.changePassword(userEmail,oldPassword,newPassword);
        new ChangePassword(userEmail).setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        //setVisible(false);
        if(userEmail.equals("admin@gmail.com"))
        {
            setVisible(false);
            new AdminHome(userEmail).setVisible(true);
        }
        
        else if(userEmail.equals("manager@gmail.com"))
        {
            setVisible(false);
            new ManagerHome(userEmail).setVisible(true);
        }
        
        else
        {
            setVisible(false);
            new StudentHome(userEmail).setVisible(true);
        }
    }//GEN-LAST:event_jBackMouseClicked

    private void txtOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPasswordActionPerformed

    private void txtOldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPasswordKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtOldPasswordKeyReleased

    private void txtNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNewPasswordKeyReleased

    private void txtConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtConfirmPasswordKeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/popupicon/warning.png");

        //int a = JOptionPane.showConfirmDialog(null,"Do you really want to close application?","Select",JOptionPane.YES_NO_OPTION);
        int a = JOptionPane.showConfirmDialog(null,"<html> <b style=\"color:red\">Do you really want to close this application?</b></html>" , "Select", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE ,icon);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void eyeOpenOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpenOldMouseClicked
        // TODO add your handling code here:
        eyeOpenOld.setVisible(false);
        eyeCloseOld.setVisible(true);
        txtOldPassword.setEchoChar((char) 0);

    }//GEN-LAST:event_eyeOpenOldMouseClicked

    private void eyeOpen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpen1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_eyeOpen1MouseClicked

    private void eyeOpenNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpenNewMouseClicked
        // TODO add your handling code here:
        eyeOpenNew.setVisible(false);
        eyeCloseNew.setVisible(true);
        txtNewPassword.setEchoChar((char) 0);

    }//GEN-LAST:event_eyeOpenNewMouseClicked

    private void eyeOpen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpen3MouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_eyeOpen3MouseClicked

    private void eyeOpenConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpenConfirmMouseClicked
        // TODO add your handling code here:
        eyeOpenConfirm.setVisible(false);
        eyeCloseConfirm.setVisible(true);
        txtConfirmPassword.setEchoChar((char) 0);

    }//GEN-LAST:event_eyeOpenConfirmMouseClicked

    private void eyeCloseNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeCloseNewMouseClicked
        // TODO add your handling code here:
        eyeOpenNew.setVisible(true);
        eyeCloseNew.setVisible(false);
        txtNewPassword.setEchoChar('*');
    }//GEN-LAST:event_eyeCloseNewMouseClicked

    private void eyeClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClose1MouseClicked
        
    }//GEN-LAST:event_eyeClose1MouseClicked

    private void jBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBack1MouseClicked

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void jBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBack2MouseClicked

    private void txtOldPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPassword2ActionPerformed

    private void txtOldPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPassword2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPassword2KeyReleased

    private void txtNewPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassword2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassword2KeyReleased

    private void txtConfirmPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPassword2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassword2KeyReleased

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void eyeOpen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpen6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeOpen6MouseClicked

    private void eyeOpen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpen7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeOpen7MouseClicked

    private void eyeClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClose2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeClose2MouseClicked

    private void jBack3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBack3MouseClicked

    private void txtOldPassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPassword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPassword3ActionPerformed

    private void txtOldPassword3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPassword3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPassword3KeyReleased

    private void txtNewPassword3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassword3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassword3KeyReleased

    private void txtConfirmPassword3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPassword3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassword3KeyReleased

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear3ActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void eyeOpen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeOpen5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeOpen5MouseClicked

    private void eyeCloseConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeCloseConfirmMouseClicked
        // TODO add your handling code here:
        eyeOpenConfirm.setVisible(true);
        eyeCloseConfirm.setVisible(false);
        txtConfirmPassword.setEchoChar('*');
    }//GEN-LAST:event_eyeCloseConfirmMouseClicked

    private void eyeCloseOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeCloseOldMouseClicked
        // TODO add your handling code here:
        eyeOpenOld.setVisible(true);
        eyeCloseOld.setVisible(false);
        txtOldPassword.setEchoChar('*');
    }//GEN-LAST:event_eyeCloseOldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blue;
    private javax.swing.JPanel blue1;
    private javax.swing.JPanel blue2;
    private javax.swing.JPanel blue3;
    private rojerusan.RSMaterialButtonRectangle btnClear;
    private rojerusan.RSMaterialButtonRectangle btnClear1;
    private rojerusan.RSMaterialButtonRectangle btnClear2;
    private rojerusan.RSMaterialButtonRectangle btnClear3;
    private rojerusan.RSMaterialButtonRectangle btnUpdate;
    private rojerusan.RSMaterialButtonRectangle btnUpdate1;
    private rojerusan.RSMaterialButtonRectangle btnUpdate2;
    private rojerusan.RSMaterialButtonRectangle btnUpdate3;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorArc2D evaluatorArc2D1;
    private javax.swing.JLabel eyeClose1;
    private javax.swing.JLabel eyeClose2;
    private javax.swing.JLabel eyeCloseConfirm;
    private javax.swing.JLabel eyeCloseNew;
    private javax.swing.JLabel eyeCloseOld;
    private javax.swing.JLabel eyeOpen1;
    private javax.swing.JLabel eyeOpen3;
    private javax.swing.JLabel eyeOpen5;
    private javax.swing.JLabel eyeOpen6;
    private javax.swing.JLabel eyeOpen7;
    private javax.swing.JLabel eyeOpenConfirm;
    private javax.swing.JLabel eyeOpenNew;
    private javax.swing.JLabel eyeOpenOld;
    private javax.swing.JLabel jBack;
    private javax.swing.JLabel jBack1;
    private javax.swing.JLabel jBack2;
    private javax.swing.JLabel jBack3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private necesario.MaterialButton materialButton1;
    private rojerusan.RSMaterialButtonCircleBeanInfo rSMaterialButtonCircleBeanInfo1;
    private rojerusan.RSMaterialButtonCircleBeanInfo rSMaterialButtonCircleBeanInfo2;
    private rojerusan.RSMaterialButtonCircleBeanInfo rSMaterialButtonCircleBeanInfo3;
    private rojerusan.RSMaterialButtonCircleBeanInfo rSMaterialButtonCircleBeanInfo4;
    private rojerusan.RSMaterialButtonCircleBeanInfo rSMaterialButtonCircleBeanInfo5;
    private rojerusan.RSMaterialButtonRectangleBeanInfo rSMaterialButtonRectangleBeanInfo1;
    private rojerusan.RSMaterialButtonRectangleBeanInfo rSMaterialButtonRectangleBeanInfo2;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtConfirmPassword2;
    private javax.swing.JPasswordField txtConfirmPassword3;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtNewPassword2;
    private javax.swing.JPasswordField txtNewPassword3;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JPasswordField txtOldPassword2;
    private javax.swing.JPasswordField txtOldPassword3;
    // End of variables declaration//GEN-END:variables
}
