/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hall.dining.managemeent.system;

import dao.UserDao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author sami
 */
public class ExpeneseCalculation extends javax.swing.JFrame {

    //String month = txtMonth.getText();
    public String numPattern = "^[0-9]*$";
    public String userEmail=null;

    /**
     * Creates new form StudentProfile
     */
    public ExpeneseCalculation() {
        initComponents();
        btnCalculate.setEnabled(false);
    }

    public ExpeneseCalculation(String email) {
        initComponents();
        userEmail = email;
        btnCalculate.setEnabled(false);
        //showData();
    }

    public void validateFields() {
        String hallClose = txtHallClose.getText();
        String mealOff = txtMealOff.getText();
        String seatRent = txtSeatRent.getText();
        String admission = txtAdmission.getText();
        String establishment = txtEstablishment.getText();
        String commonRoom = txtCommonRoom.getText();
        String literature = txtLiterature.getText();
        String hallUnion = txtHallUnion.getText();
        String hallLibrary = txtHallLibrary.getText();
        String tv = txtTV.getText();
        String genaretor = txtGenaretor.getText();
        String waterSupply = txtWaterSupply.getText();
        String religion = txtReligion.getText();

        if (hallClose.matches(numPattern) && mealOff.matches(numPattern) && admission.matches(numPattern) && establishment.matches(numPattern) && commonRoom.matches(numPattern)
                && literature.matches(numPattern) && hallUnion.matches(numPattern) && hallLibrary.matches(numPattern) && tv.matches(numPattern) && genaretor.matches(numPattern)
                && waterSupply.matches(numPattern) && religion.matches(numPattern) && seatRent.matches(numPattern)) {

            if (!hallClose.equals("") && !mealOff.equals("") && !admission.equals("") && !establishment.equals("") && !commonRoom.equals("")
                    && !literature.equals("") && !hallUnion.equals("") && !hallLibrary.equals("") && !tv.equals("") && !genaretor.equals("")
                    && !waterSupply.equals("") && !religion.equals("") && !seatRent.equals("")) {
                
                btnCalculate.setEnabled(true);
            }
        } 
        
        else {
            btnCalculate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jCTextField16 = new app.bolivia.swing.JCTextField();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBack = new javax.swing.JLabel();
        txtMonth = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHallClose = new app.bolivia.swing.JCTextField();
        txtUtensil = new app.bolivia.swing.JCTextField();
        txtAdmission = new app.bolivia.swing.JCTextField();
        txtHallLibrary = new app.bolivia.swing.JCTextField();
        txtMealOff = new app.bolivia.swing.JCTextField();
        txtReligion = new app.bolivia.swing.JCTextField();
        txtGenaretor = new app.bolivia.swing.JCTextField();
        txtTV = new app.bolivia.swing.JCTextField();
        txtLiterature = new app.bolivia.swing.JCTextField();
        txtCommonRoom = new app.bolivia.swing.JCTextField();
        txtHallUnion = new app.bolivia.swing.JCTextField();
        txtSeatRent = new app.bolivia.swing.JCTextField();
        txtEstablishment = new app.bolivia.swing.JCTextField();
        txtWaterSupply = new app.bolivia.swing.JCTextField();
        btnCalculate = new rojerusan.RSMaterialButtonRectangle();
        btnClear = new rojerusan.RSMaterialButtonRectangle();
        jLabel19 = new javax.swing.JLabel();

        jLabel12.setText("jLabel7");

        jLabel14.setText("jLabel7");

        jCTextField2.setText("jCTextField1");

        jCTextField5.setText("jCTextField1");

        jCTextField16.setText("jCTextField1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel1.setText("Month *");

        jLabel2.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel2.setText("Total Days of Hall Close *");

        jLabel3.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel3.setText("Total Days of Meal Off  *");

        jLabel4.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel4.setText("Admission");

        jLabel5.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel5.setText("Utensil");

        jLabel6.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel6.setText("Establishment");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dyuthi", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sidebarIcon/icons8-calculate-50.png"))); // NOI18N
        jLabel9.setText("Hall Dues Calculation");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack.setForeground(new java.awt.Color(255, 255, 255));
        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack.setText("Back");
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        jPanel2.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        txtMonth.setFont(new java.awt.Font("Mukti Narrow", 1, 17)); // NOI18N
        txtMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel7.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel7.setText("Common Room");

        jLabel8.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel8.setText("Literature & Culture");

        jLabel10.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel10.setText("Hall Union");

        jLabel11.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel11.setText("Hall Library");

        jLabel13.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel13.setText("Seat Rent");

        jLabel15.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel15.setText("TV/Dish Antena");

        jLabel16.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel16.setText("Genaretor");

        jLabel17.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel17.setText("Water Supply");

        jLabel18.setFont(new java.awt.Font("Z003", 1, 20)); // NOI18N
        jLabel18.setText("Religion");

        txtHallClose.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtHallClose.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtHallClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHallCloseKeyReleased(evt);
            }
        });

        txtUtensil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtUtensil.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtUtensil.setPlaceholder("15 tk.");
        txtUtensil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUtensilKeyReleased(evt);
            }
        });

        txtAdmission.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtAdmission.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtAdmission.setPlaceholder("10 tk.");
        txtAdmission.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdmissionKeyReleased(evt);
            }
        });

        txtHallLibrary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtHallLibrary.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtHallLibrary.setPlaceholder("10 tk.");
        txtHallLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHallLibraryActionPerformed(evt);
            }
        });
        txtHallLibrary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHallLibraryKeyReleased(evt);
            }
        });

        txtMealOff.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtMealOff.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtMealOff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMealOffKeyReleased(evt);
            }
        });

        txtReligion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReligion.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtReligion.setPlaceholder("10 tk.");
        txtReligion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReligionKeyReleased(evt);
            }
        });

        txtGenaretor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtGenaretor.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtGenaretor.setPlaceholder("10 tk.");
        txtGenaretor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenaretorKeyReleased(evt);
            }
        });

        txtTV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtTV.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtTV.setPlaceholder("5 tk.");
        txtTV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTVKeyReleased(evt);
            }
        });

        txtLiterature.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtLiterature.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtLiterature.setPlaceholder("10 tk");
        txtLiterature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLiteratureKeyReleased(evt);
            }
        });

        txtCommonRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtCommonRoom.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtCommonRoom.setPlaceholder("80 tk.");
        txtCommonRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCommonRoomKeyReleased(evt);
            }
        });

        txtHallUnion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtHallUnion.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtHallUnion.setPlaceholder("10 tk.");
        txtHallUnion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHallUnionKeyReleased(evt);
            }
        });

        txtSeatRent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSeatRent.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtSeatRent.setPlaceholder("50 tk.");
        txtSeatRent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeatRentKeyReleased(evt);
            }
        });

        txtEstablishment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtEstablishment.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtEstablishment.setPlaceholder("250 tk");
        txtEstablishment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstablishmentKeyReleased(evt);
            }
        });

        txtWaterSupply.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtWaterSupply.setFont(new java.awt.Font("Mukti Narrow", 1, 20)); // NOI18N
        txtWaterSupply.setPlaceholder("10 tk.");
        txtWaterSupply.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWaterSupplyKeyReleased(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(255, 51, 51));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-cross-30.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHallLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCommonRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUtensil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMealOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHallClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeatRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGenaretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHallUnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWaterSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHallClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMealOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSeatRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUtensil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCommonRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHallUnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHallLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtGenaretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtWaterSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*public void showData()
    {
        User user = null;
        user = UserDao.getAllData(userEmail);
        lb_name.setText(user.getName());
        lb_roll.setText(user.getRoll());
        lb_boarder.setText(user.getBoarder());
        lb_email.setText(userEmail);
        lb_mobileNumber.setText(user.getMobileNumber());
        lb_securityQuestion.setText(user.getSecurityQuestion());
    }*/

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentHome(userEmail).setVisible(true);
    }//GEN-LAST:event_jBackMouseClicked

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        int hallClose = Integer.parseInt(txtHallClose.getText());
        int mealOff = Integer.parseInt(txtMealOff.getText());
        int admission = Integer.parseInt(txtAdmission.getText());
        int establishment = Integer.parseInt(txtEstablishment.getText());
        int commonRoom = Integer.parseInt(txtCommonRoom.getText());
        int literature = Integer.parseInt(txtLiterature.getText());
        int hallUnion = Integer.parseInt(txtHallUnion.getText());
        int hallLibrary = Integer.parseInt(txtHallLibrary.getText());
        int tv = Integer.parseInt(txtTV.getText());
        int genaretor = Integer.parseInt(txtGenaretor.getText());
        int waterSupply = Integer.parseInt(txtWaterSupply.getText());
        int religion = Integer.parseInt(txtReligion.getText());
        int seatRent = Integer.parseInt(txtSeatRent.getText());

        String month = txtMonth.getSelectedItem().toString();
        int intMonth = 0;

        if (month.equals("January") || month.equals("March") || month.equals("May") || month.equals("July")
                || month.equals("August") || month.equals("October") || month.equals("December")) {
            intMonth = 31;
        } else if (month.equals("February - 28")) {
            intMonth = 28;
        } else if (month.equals("February - 29")) {
            intMonth = 29;
        } else {
            intMonth = 30;
        }

        int perDayMeal = 55;
        int monthlyFeast = 50;
        int total = admission + establishment + commonRoom + literature + hallUnion + hallLibrary + tv + genaretor + waterSupply + religion + seatRent + monthlyFeast;
        int messing = (intMonth - hallClose) * perDayMeal;
        total = total + messing;
        int refund = mealOff * 43; // 12 tk cut off per day meal off .

        ImageIcon icon = new ImageIcon("src/popupicon/money.png");

        JOptionPane.showMessageDialog(null, "Your monthly dues: " + Integer.toString(total) + " tk. \n" + "You will get rufund " + Integer.toString(refund) + " tk. on next month", "Message", JOptionPane.INFORMATION_MESSAGE, icon);


    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtHallClose.setText("");
        txtMealOff.setText("");
        txtAdmission.setText("");
        txtUtensil.setText("");
        txtEstablishment.setText("");
        txtCommonRoom.setText("");
        txtLiterature.setText("");
        txtHallUnion.setText("");
        txtHallLibrary.setText("");
        txtTV.setText("");
        txtGenaretor.setText("");
        txtWaterSupply.setText("");
        txtReligion.setText("");
        txtSeatRent.setText("");
        
        btnCalculate.setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtHallLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHallLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHallLibraryActionPerformed

    private void txtHallCloseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHallCloseKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtHallCloseKeyReleased

    private void txtMealOffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMealOffKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtMealOffKeyReleased

    private void txtSeatRentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatRentKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtSeatRentKeyReleased

    private void txtAdmissionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdmissionKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtAdmissionKeyReleased

    private void txtUtensilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtensilKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtUtensilKeyReleased

    private void txtEstablishmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstablishmentKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEstablishmentKeyReleased

    private void txtCommonRoomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommonRoomKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtCommonRoomKeyReleased

    private void txtLiteratureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLiteratureKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtLiteratureKeyReleased

    private void txtHallUnionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHallUnionKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtHallUnionKeyReleased

    private void txtHallLibraryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHallLibraryKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtHallLibraryKeyReleased

    private void txtTVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTVKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTVKeyReleased

    private void txtGenaretorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenaretorKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtGenaretorKeyReleased

    private void txtWaterSupplyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaterSupplyKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtWaterSupplyKeyReleased

    private void txtReligionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReligionKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtReligionKeyReleased

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/popupicon/warning.png");

        //int a = JOptionPane.showConfirmDialog(null,"Do you really want to close application?","Select",JOptionPane.YES_NO_OPTION);
        int a = JOptionPane.showConfirmDialog(null,"<html> <b style=\"color:red\">Do you really want to close this application?</b></html>" , "Select", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE ,icon);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpeneseCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpeneseCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpeneseCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpeneseCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpeneseCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCalculate;
    private rojerusan.RSMaterialButtonRectangle btnClear;
    private javax.swing.JLabel jBack;
    private app.bolivia.swing.JCTextField jCTextField16;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.PopupMenu popupMenu1;
    private app.bolivia.swing.JCTextField txtAdmission;
    private app.bolivia.swing.JCTextField txtCommonRoom;
    private app.bolivia.swing.JCTextField txtEstablishment;
    private app.bolivia.swing.JCTextField txtGenaretor;
    private app.bolivia.swing.JCTextField txtHallClose;
    private app.bolivia.swing.JCTextField txtHallLibrary;
    private app.bolivia.swing.JCTextField txtHallUnion;
    private app.bolivia.swing.JCTextField txtLiterature;
    private app.bolivia.swing.JCTextField txtMealOff;
    private javax.swing.JComboBox<String> txtMonth;
    private app.bolivia.swing.JCTextField txtReligion;
    private app.bolivia.swing.JCTextField txtSeatRent;
    private app.bolivia.swing.JCTextField txtTV;
    private app.bolivia.swing.JCTextField txtUtensil;
    private app.bolivia.swing.JCTextField txtWaterSupply;
    // End of variables declaration//GEN-END:variables
}
