/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hall.dining.managemeent.system;

import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author sami
 */
public class HallDiningManagemeentSystem extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public HallDiningManagemeentSystem() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingLabel = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingLabel.setText("Loading...");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        loadingValue.setText("0 %");
        jPanel1.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, -1));

        loadingBar.setBackground(new java.awt.Color(255, 255, 255));
        loadingBar.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 890, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/test.jpg"))); // NOI18N
        jLabel1.setText("jLabel2");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/test.jpg"))); // NOI18N

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/test.jpg"))); // NOI18N

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   // UIManager.put ("progressBar.selectBackground",Color.BLUE);  
  
   //UIManager.put("loadingBar.selectionBackground",Color.BLUE);
   //UIManager.put("loadingBar.selectionForeground",Color.WHITE);


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HallDiningManagemeentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HallDiningManagemeentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HallDiningManagemeentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HallDiningManagemeentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
        HallDiningManagemeentSystem sp = new HallDiningManagemeentSystem();
        sp.setVisible(true);
        try{
            for(int i=0;i<=100;i++)
            {
                 Thread.sleep(100);
                 sp.loadingValue.setText(i +"%");
                 
                 if(i==10)
                 {
                     sp.loadingLabel.setText("Turning ON Modules...");
                 }
                 
                 if(i==20)
                 {
                     sp.loadingLabel.setText("Loading Modules...");
                 }
                 
                 if(i==50)
                 {
                     sp.loadingLabel.setText("Connecting to Database...");
                 }
                 
                 if(i==70)
                 {
                     sp.loadingLabel.setText("Connection Successful!...");
                 }
                 
                 if(i==80)
                 {
                     sp.loadingLabel.setText("Launching Application...");
                 }
                 
                 sp.loadingBar.setValue(i);
            }
            sp.setVisible(false);
            new Login().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //setVisible(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
