/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hall.dining.managemeent.system;

import dao.UserDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.UserFeedback;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author sami
 */
public class SeeFeedbackManager extends javax.swing.JFrame {

    String userEmail = null;

    /**
     * Creates new form VerifyUsers
     */
    public SeeFeedbackManager() {
        
        //tableColumnEdit();
        initComponents();
        tableColumnEdit();
        showPieChart();
    }

    public SeeFeedbackManager(String userCurrentMail) {
        
        //tableColumnEdit();
        initComponents();
        tableColumnEdit();
        userEmail = userCurrentMail;
        showPieChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void tableColumnEdit()
    {
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(5);
        columnModel.getColumn(2).setPreferredWidth(5);
        columnModel.getColumn(3).setPreferredWidth(500);
    }
    
  
    public void getAllRecordsFeedback(String email) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<UserFeedback> list = UserDao.getAllRecordFeedback(email);
        Iterator<UserFeedback> itr = list.iterator();
        while (itr.hasNext()) {
            UserFeedback userObj = itr.next();
            //if(!userObj.getEmail().equals("admin@gmail.com")) //can't change the status of admin
            //{
            dtm.addRow(new Object[]{userObj.getDate(), userObj.getTime(), userObj.getRating(), userObj.getComment()});

            //}
        }
    }

    public void showPieChart() {

        //create dataset
        DefaultPieDataset barDataset = new DefaultPieDataset();

        /*barDataset.setValue("IPhone 5s" , Double.valueOf(20));  
        barDataset.setValue("SamSung Grand" , Double.valueOf(20));   
        barDataset.setValue("MotoG" , Double.valueOf(40));    
        barDataset.setValue("Nokia Lumia" , Double.valueOf(10));*/
        int issue_count = 4;
        try {
            //Connection con =DBConnection.getConnection();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dms", "root", "password");
           
            PreparedStatement pst = con.prepareStatement("select rating, count(*) as issue_count from studentFeedback group by rating");
            //Statement st  =  (Statement) con.createStatement();
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                barDataset.setValue(rs.getString("rating"), new Double(rs.getDouble("issue_count")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //create chart
        JFreeChart piechart = ChartFactory.createPieChart("Student Reaction", barDataset, false, true, false);//explain

        PiePlot piePlot = (PiePlot) piechart.getPlot();

        //changing pie chart blocks colors
        piePlot.setSectionPaint("IPhone 5s", new Color(255, 255, 102));
        piePlot.setSectionPaint("SamSung Grand", new Color(102, 255, 102));
        piePlot.setSectionPaint("MotoG", new Color(255, 102, 153));
        piePlot.setSectionPaint("Nokia Lumia", new Color(0, 204, 204));

        piePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelPieChart.removeAll();
        panelPieChart.add(barChartPanel, BorderLayout.CENTER);
        panelPieChart.validate();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estiloTablaHeader1 = new rojerusan.necesario.EstiloTablaHeader();
        estiloTablaHeader2 = new rojerusan.necesario.EstiloTablaHeader();
        textBox1 = new org.jfree.text.TextBox();
        textBlock1 = new org.jfree.text.TextBlock();
        jCommonResources1 = new org.jfree.resources.JCommonResources();
        dayAndMonthRule1 = new org.jfree.date.DayAndMonthRule();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new rojerusan.RSTableMetro();
        panelPieChart = new javax.swing.JPanel();
        btnShowAllData = new rojerusan.RSMaterialButtonRectangle();
        txtToDateSeach = new rojeru_san.componentes.RSDateChooser();
        txtFromDateSeach = new rojeru_san.componentes.RSDateChooser();
        btnSearch1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 242));

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sidebarIcon/icons8-80%-50.png"))); // NOI18N
        jLabel1.setText(" Feedback Analyze");

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jBack.setForeground(new java.awt.Color(255, 255, 255));
        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8_Rewind_48px.png"))); // NOI18N
        jBack.setText("Back");
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        jPanel3.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExtraIcon/icons8-cross-30.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 811, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Reaction", "Comment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 820, -1));

        panelPieChart.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelPieChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 340));

        btnShowAllData.setBackground(new java.awt.Color(255, 51, 51));
        btnShowAllData.setText("SHow all data");
        btnShowAllData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllDataActionPerformed(evt);
            }
        });
        jPanel2.add(btnShowAllData, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 150, 50));

        txtToDateSeach.setFormatoFecha("yyyy-MM-dd");
        txtToDateSeach.setPlaceholder("To Search Date");
        jPanel2.add(txtToDateSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 180, -1));

        txtFromDateSeach.setFormatoFecha("yyyy-MM-dd");
        txtFromDateSeach.setPlaceholder("From Search Date");
        jPanel2.add(txtFromDateSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 180, -1));

        btnSearch1.setBackground(new java.awt.Color(255, 51, 51));
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 100, 50));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(780, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(780, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1330, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        if (userEmail.equals("admin@gmail.com")) {
            new AdminHome(userEmail).setVisible(true);
        } else if (userEmail.equals("manager@gmail.com")) {
            new ManagerHome(userEmail).setVisible(true);
        } else {
            new StudentHome(userEmail).setVisible(true);
        }
    }//GEN-LAST:event_jBackMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getAllRecordsFeedback(""); // load all data
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        /*int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String email = model.getValueAt(index,2).toString();
        //String status =model.getValueAt(index, 6).toString();

        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete this email "+email+"?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            UserDao.deleteAccount(email);
            setVisible(false);
            new SeeFeedbackManager().setVisible(true);
        }
        else
        {
            setVisible(true);
        }*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void btnShowAllDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllDataActionPerformed
          getAllRecordsFeedback("");
          showPieChart();
    }//GEN-LAST:event_btnShowAllDataActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        
        DefaultPieDataset barDataset = new DefaultPieDataset();
        Format f = new SimpleDateFormat("yyyy-MM-dd");
        
        String toDate = f.format(txtToDateSeach.getDatoFecha());
        String fromDate = f.format(txtFromDateSeach.getDatoFecha()); 
        //System.out.println(toDate);
        //System.out.println(fromDate);
        /*barDataset.setValue("IPhone 5s" , Double.valueOf(20));  
        barDataset.setValue("SamSung Grand" , Double.valueOf(20));   
        barDataset.setValue("MotoG" , Double.valueOf(40));    
        barDataset.setValue("Nokia Lumia" , Double.valueOf(10));*/
        int issue_count = 4;
        try {
            //Connection con =DBConnection.getConnection();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dms", "root", "password");
            //PreparedStatement pst = con.prepareStatement("select book_name, count(*) as issue_count from issue_book_details group by book__id");
            PreparedStatement pst = con.prepareStatement("select rating, count(*) as issue_count from studentFeedback where date between '"+fromDate+"' and '"+toDate+"' group by rating");
            //Statement st  =  (Statement) con.createStatement();
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                barDataset.setValue(rs.getString("rating"), new Double(rs.getDouble("issue_count")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //create chart
        JFreeChart piechart = ChartFactory.createPieChart("Student Reaction", barDataset, false, true, false);//explain

        PiePlot piePlot = (PiePlot) piechart.getPlot();

        //changing pie chart blocks colors
        piePlot.setSectionPaint("IPhone 5s", new Color(255, 255, 102));
        piePlot.setSectionPaint("SamSung Grand", new Color(102, 255, 102));
        piePlot.setSectionPaint("MotoG", new Color(255, 102, 153));
        piePlot.setSectionPaint("Nokia Lumia", new Color(0, 204, 204));

        piePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelPieChart.removeAll();
        panelPieChart.add(barChartPanel, BorderLayout.CENTER);
        panelPieChart.validate();
        
        
        /***********************Now workking of table update*******************/
           //jTable1.setVisible(false);
           try {
            //Connection con =DBConnection.getConnection();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dms", "root", "password");
            //PreparedStatement pst = con.prepareStatement("select book_name, count(*) as issue_count from issue_book_details group by book__id");
            PreparedStatement pst = con.prepareStatement("select * from studentFeedback where date between '"+fromDate+"' and '"+toDate+"'");
            //Statement st  =  (Statement) con.createStatement();
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            Object[] row;
            
            while(rs.next()){
                row = new Object[4];
                row[0] = rs.getString(3);
                row[1] = rs.getString(4);
                row[2] = rs.getString(5);
                row[3] = rs.getString(6);
                
                model.addRow(row);
            }
        } 
           
        catch (Exception e) {
            e.printStackTrace();
        }
          //jTable1.setVisible(true);
           //DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/popupicon/warning.png");

        //int a = JOptionPane.showConfirmDialog(null,"Do you really want to close application?","Select",JOptionPane.YES_NO_OPTION);
        int a = JOptionPane.showConfirmDialog(null,"<html> <b style=\"color:red\">Do you really want to close this application?</b></html>" , "Select", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE ,icon);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeFeedbackManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeFeedbackManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeFeedbackManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeFeedbackManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeeFeedbackManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnSearch1;
    private rojerusan.RSMaterialButtonRectangle btnShowAllData;
    private org.jfree.date.DayAndMonthRule dayAndMonthRule1;
    private rojerusan.necesario.EstiloTablaHeader estiloTablaHeader1;
    private rojerusan.necesario.EstiloTablaHeader estiloTablaHeader2;
    private javax.swing.JLabel jBack;
    private org.jfree.resources.JCommonResources jCommonResources1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro jTable1;
    private javax.swing.JPanel panelPieChart;
    private org.jfree.text.TextBlock textBlock1;
    private org.jfree.text.TextBox textBox1;
    private rojeru_san.componentes.RSDateChooser txtFromDateSeach;
    private rojeru_san.componentes.RSDateChooser txtToDateSeach;
    // End of variables declaration//GEN-END:variables
}
